trigger:
- main

variables:
  dockerRegistryServiceConnection: 'ACR–TodoApp'    # Your Docker Registry service connection
  azureServiceConnection: 'Azure–Todo-App'            # Your Azure Resource Manager service connection
  acrName: 'todocrdev123'                              # e.g. todoregistry123
  acrLoginServer: 'todocrdev123.azurecr.io'            # Replace with actual ACR login server
  imageRepositoryBackend: 'todolist-backend'
  dockerfilePathBackend: '$(Build.SourcesDirectory)/backend/Dockerfile'
  containerAppName: 'todo-api-app-dev'
  containerAppResourceGroup: 'rg-todo-dev'
  containerAppEnv: 'Todoapp-Environment'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push backend image
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and Push Backend Image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepositoryBackend)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePathBackend)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure Container App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      name: DeployContainerApp
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt

          echo "Updating Azure Container App revision..."
          az containerapp update \
            --name $(containerAppName) \
            --resource-group $(containerAppResourceGroup) \
            --image $(acrLoginServer)/$(imageRepositoryBackend):$(tag) \
            --cpu 0.5 \
            --memory 1.0Gi

